"""Compatibility wrappers for graph-transformation helpers."""

from quantum_graph_search._graph_process import (
    bye_cp,
    bye_nb,
    bye_st,
    count_edges,
    fill,
    fill_in,
    fill_inplace,
    fill_out,
    fill_out_upto,
    fill_to_total_edges,
    pick_high_degree_nodes,
    pick_low_degree_nodes,
    pick_medium_degree_nodes,
    pick_nodes,
    remove_inside_outside_edges,
    remove_neighborhood_edges,
    remove_non_marked_edges,
)

__all__ = [
    "bye_cp",
    "bye_nb",
    "bye_st",
    "count_edges",
    "fill",
    "fill_in",
    "fill_inplace",
    "fill_out",
    "fill_out_upto",
    "fill_to_total_edges",
    "pick_high_degree_nodes",
    "pick_low_degree_nodes",
    "pick_medium_degree_nodes",
    "pick_nodes",
    "remove_inside_outside_edges",
    "remove_neighborhood_edges",
    "remove_non_marked_edges",
]
